### ISSUE TITLE
Add testing information to the README file

### ISSUE THREAD

**Issue by kriston-burnstein** [kriston-burnstein/parkside-paradise-virtual-walks-app#29]
**Objective:**
Integrate clear documentation for the testing procedures within the app by updating the README file. This includes information on running tests, generating coverage reports, and guidelines for writing tests.

**Tasks:**
- [ ]  Create a "Testing" section in the README file.
- [ ]  Detail the tools and libraries used for testing.
- [ ]  Provide instructions for running tests locally.
- [ ]  Explain how to generate and locate coverage reports.
- [ ]  Mention the test directory for guidance on writing tests.
- [ ]  Link to any documentation necessary. 

**Future Scope:**
As more testing functionalities or procedures are introduced, continue to update the README file to reflect the latest practices and guidelines.
